services:
  - type: web
    name: gyscbackend
    runtime: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://globalsustainabilitycouncil.netlify.app
